name: nearwork
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_maps_flutter: ^2.17.1
  url_launcher: ^6.3.2

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/